### ISSUE TITLE
$like operator isn't working as intended

### ISSUE THREAD

**Issue by tanvirrb** [hashemirafsan/elasticsearch-dynamic-query#1]
I was trying to run a query to get some partial data from elasitcsearch. But it's returning an empty array. 
Tried query:
```js
{
        "name": {
            "type": "TEXT",
            "conditions": {
                "$like": "tanvirr"
            }
        }
    }
```

**Comment by hashemirafsan** [comment]
This issue can be generate based on field type (text / keyword). In latest version resolved the some issues based operator. Hopefully it will be fixed.
